### ISSUE TITLE
library looks awesome, license too restrictive

### ISSUE THREAD

**Issue by davydotcom** [fbacchella/ipmilib#2]
Would love to use this library but the license is too restrictive. Any chance this license could be changed to MIT or Apache license?

**Comment by fbacchella** [comment]
It's impossible for me to change the licence. See http://www.veraxsystems.com/en/products/free-ipmi-library-java.

You should ask them about the licence.

But if they agree, I will be pleased to change it to an Apache/BSD/MIT licence.
